version: '3'
services:
  python:
    container_name: 'python.cpu.nlp-tools'
    image: akitenkrad/python.cpu:latest
    platform: linux/amd64 # for Apple Mac M1
    user: root
    tty: true
    volumes:
      - ./:/workplace:cached
      - data:/data
    environment:
      TZ: Asia/Tokyo
    working_dir: /workplace
volumes:
  data:
    external: True
